### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SwastikC** [vsquicciarini/alpha-ubbi#1]
Hi. I am getting this error after installing the package :(

![test](https://user-images.githubusercontent.com/68861854/173175650-9845c314-1f87-4df2-8a64-dc1fd544dc67.png)

**Comment by vsquicciarini** [comment]
Hi, thanks for contacting me! I'm sorry to hear that. The problem lies in the fact that your system is calling the wrong tap package. There are unfortunately two packages named tap, and the one we are using is the following: 
https://github.com/mfouesneau/tap
You can install it using the command:
pip install git+https://github.com/mfouesneau/tap
The package that is installed in your site-packages folder is likely this one instead:
https://pypi.org/project/tap.py/.
Indeed, in my tap.py file there is no such line.
I hope this was helpful.

**Comment by SwastikC** [comment]
Thank you so much :)
This is working now.
I have one more question : " Can madys be used for estimating the ages of directly imaged planet and brown-dwarf hosting stars" ? 
Swastik

**Comment by vsquicciarini** [comment]
Great, I'm glad to hear that :)
Well, as we discuss in the paper, it is always possible to estimate the ages of single stars with MADYS (if it is in Gaia and it has reliable photometry), but some caveats apply: if the star is of F-type or G-type, the estimate is usually accurate; if the star is of K-type or M-type, the resulting age is very likely underestimated; if the star is earlier than the F-type, it is likely already on the main sequence, and deriving an accurate age estimate is very tough if the true age is higher than a few Myr. Personally, for directly imaged stars, which are usually found in clusters, associations or moving groups, I look for comoving stars into Gaia and use MADYS on those stars (I assume that their ages are similar). In any case, I suggest to compute the age with more than one model: if the spread between their predictions is reasonable, then the age is probably well constrained.
Vito
