### ISSUE TITLE
All-NaN slice encountered

### ISSUE THREAD

**Issue by YxmMu** [vsquicciarini/alpha-ubbi#2]
### Hi,  I encountered the following problems when testing example.When I convert the model from'bhac15'to' parsec ', the returned results are all null  values
`els_file='els.txt'`

`els_obj=SampleObject(els_file,id_type='EDR3',verbose=0,ext_map='leike')
result=els_obj.get_params('parsec',age_range=[1,300],n_try=200,save_maps=True)`

/home/yang/anaconda3/envs/madys/lib/python3.7/site-packages/madys/madys.py:3299: RuntimeWarning: All-NaN slice encountered
  if np.nanmin(np.abs(iso_data_r[use_i,w[h]]-ph))<0.2: b[h]=True #if the best theor. match is more than 0.2 mag away, discards it

**Comment by vsquicciarini** [comment]
Hi! The problem lies in the fact that in the alpha release I have not made available the full PARSEC grids. As mentioned at the beginning of the notebook, for the moment only ages between [500, 7000] Myr are available for PARSEC models. That's why an age_range between 1 Myr and 300 Myr results in a full-nan slice. In any case, I will soon make public a beta version with the full set of models :)

**Comment by YxmMu** [comment]
> Hi! The problem lies in the fact that in the alpha release I have not made available the full PARSEC grids. As mentioned at the beginning of the notebook, for the moment only ages between [500, 7000] Myr are available for PARSEC models. That's why an age_range between 1 Myr and 300 Myr results in a full-nan slice. In any case, I will soon make public a beta version with the full set of models :)



Thank you for your answer. This program is  helpful to my research, so I hope you can complete it smoothly. Looking forward to the release of the beta version :)

**Comment by vsquicciarini** [comment]
Thank you very much! I'm so glad to hear that my tool is helpful for your research :) You'll find the beta version here in a few days, hopefully!
